### ISSUE TITLE
 Unknown resource type: 'registry_value'

### ISSUE THREAD

**Issue by coryarobbins** [puppetlabs/puppetlabs-chocolatey#353]
## Describe the Bug
When I attempt to use the puppet agent, I receive the following:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'registry_value' (file: /etc/puppetlabs/code/environments/production/modules/chocolatey/manifests/install.pp, line: 38, column: 3) on node desktop-pmmjds3.wftigers.org
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/rest.rb:48:in `rescue in find'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/rest.rb:9:in `find'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:230:in `find'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:731:in `block in retrieve_new_catalog'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/util.rb:518:in `block in thinmark'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/util.rb:517:in `thinmark'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:730:in `retrieve_new_catalog'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:84:in `retrieve_catalog'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:269:in `prepare_and_retrieve_catalog'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:430:in `run_internal'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:341:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:85:in `block (6 levels) in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet.rb:288:in `override'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:84:in `block (5 levels) in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/3.2.0/timeout.rb:196:in `timeout'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:83:in `block (4 levels) in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:23:in `lock'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:73:in `block (3 levels) in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:164:in `with_client'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:69:in `block (2 levels) in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:129:in `run_in_fork'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:68:in `block in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/application.rb:174:in `controlled_run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:49:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:437:in `onetime'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:394:in `block in run_command'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet.rb:288:in `override'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:391:in `run_command'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/application.rb:423:in `block in run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/util.rb:706:in `exit_on_fail'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/application.rb:423:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:145:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:79:in `execute'
C:/Program Files/Puppet Labs/Puppet/puppet/bin/puppet:5:in `<main>'
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

I have the registry module installed.

`puppet module list --environment production

/etc/puppetlabs/code/environments/production/site-modules
├── adhoc (???)
├── profile (???)
└── role (???)
/etc/puppetlabs/code/environments/production/modules
├── puppetlabs-acl (v5.0.0)
├── puppetlabs-apt (v9.4.0)
├── puppetlabs-chocolatey (v8.0.0)
├── puppetlabs-concat (v9.0.2)
├── puppetlabs-facts (v1.4.0)
├── puppetlabs-inifile (v6.1.1)
├── puppetlabs-powershell (v6.0.0)
├── puppetlabs-puppet_agent (v4.19.0)
├── puppetlabs-pwshlib (v1.1.1)
├── puppetlabs-reboot (v5.0.0)
├── puppetlabs-registry (v5.0.1)
├── puppetlabs-ruby_task_helper (v0.6.1)
└── puppetlabs-stdlib (v9.6.0)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)
`

## Expected Behavior
Package installs.

## Steps to Reproduce

Install the following modules:
`mod 'puppetlabs/stdlib',  '9.6.0'
mod 'puppetlabs/concat',  '9.0.2'
mod 'puppetlabs-chocolatey', '8.0.0'
mod 'puppetlabs-powershell', '6.0.0'
mod 'puppetlabs-registry', '5.0.1'
mod 'puppetlabs-ruby_task_helper', '0.6.1'
mod 'puppetlabs-acl', '5.0.0'
mod 'puppetlabs-reboot', '5.0.0'
mod 'puppetlabs-puppet_agent', '4.19.0'
mod 'puppetlabs-apt', '9.4.0'
mod 'puppetlabs-facts', '1.4.0'
mod 'puppetlabs-inifile', '6.1.1'
mod 'puppetlabs-pwshlib', '1.1.1'
`

Add the following to site.pp:
`
include chocolatey
node default {
  # This is where you can declare classes for all nodes.
  # Example:
  #   class { 'my_class': }
  if $::kernel == 'windows' {
    Package { provider => chocolatey, }
  }
  class {'chocolatey':
    log_output => true,
  }
  package { 'etcher':
    ensure   => latest,
    provider => 'chocolatey',
  }
}
`
On the windows agent, run:
`puppet agent --test --trace --debug --verbose`

## Environment
 - Version 8.0.0
 - Platform  Ubuntu 22.04 master, Windows 11 23H2 agent

## Additional Context
I'm very new to Puppet.  I'ms sure I'm probably just missing something stupid.

**Comment by coryarobbins** [comment]
Apologies.  I think my environment must have been cached.  Another reboot of the server fixed that issue.
